[build]
  command = "yarn run build:prod"
  publish = ".next"
  functions = "netlify/dist/functions"

[build.environment]
  NODE_VERSION = "20.9.0"

[dev]
  command = "yarn dev:next"
  port = 8888
  targetPort = 3000
  framework = "#custom"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/dist/functions"
